"""Radiometric calibration and processing pipeline for Sentinel-1 GRD.

Implements the official ESA radiometric calibration chain for Sentinel-1 GRD
products, supporting both client-side Route B (raw DN + ESA LUT) and
CDSE Process API (SIGMA0_ELLIPSOID linear power to dB).

Official ESA Reference:
    "Radiometric Calibration of S-1 Level-1 Products Generated by the S-1 IPF"
    Document: ESA-EOPG-CSCOP-TN-0002 / S1-TN-MDA-52-7440.

Equation:
    sigma0_linear = |DN|^2 / A_sigma^2
    sigma0_dB = 10 * log10(max(sigma0_linear, epsilon))

Operational Channel Order (EXP-06 Contract):
    Ch0 = VH (Cross-Polarization)
    Ch1 = VV (Co-Polarization)

No model inference or training logic is contained in this module.
"""

from __future__ import annotations

import logging
from typing import Optional, Sequence, Tuple, Union

import numpy as np

logger = logging.getLogger(__name__)

# Default epsilon for dB conversion: -70 dB floor, well below S1 NESZ (-25 to -35 dB)
DEFAULT_EPSILON = 1e-7

# EXP-06 Operational Mapping constants
OPERATIONAL_CH0_POLARIZATION = "VH"
OPERATIONAL_CH1_POLARIZATION = "VV"
OPERATIONAL_STACK_ORDER = (OPERATIONAL_CH0_POLARIZATION, OPERATIONAL_CH1_POLARIZATION)


def calibrate_dn_to_sigma0_linear(
    dn: np.ndarray,
    lut_sigma: Union[float, np.ndarray],
    nodata_mask: Optional[np.ndarray] = None,
) -> np.ndarray:
    """Calibrate raw digital numbers (DN) to linear backscatter coefficient (sigma0).

    Applies the ESA formula:
        sigma0_linear = DN^2 / A_sigma^2

    Args:
        dn: Raw integer or float digital numbers (amplitude), shape (H, W).
        lut_sigma: Calibration factor A_sigma (scalar or array matching dn shape).
        nodata_mask: Optional boolean mask where True indicates invalid/nodata pixels.

    Returns:
        sigma0_linear: Dimensionless linear backscatter coefficient as float32 array.

    Raises:
        ValueError: If dn has negative values, or lut_sigma is non-positive or invalid shape.
    """
    dn_arr = np.asarray(dn, dtype=np.float32)
    lut_arr = np.asarray(lut_sigma, dtype=np.float32)

    if np.any(lut_arr <= 0):
        raise ValueError("Calibration factor A_sigma must be strictly positive (> 0).")

    if lut_arr.ndim > 0 and lut_arr.shape != dn_arr.shape:
        raise ValueError(
            f"lut_sigma shape {lut_arr.shape} does not match dn shape {dn_arr.shape}."
        )

    # Compute sigma0_linear = DN^2 / A_sigma^2
    sigma0_linear = (dn_arr ** 2) / (lut_arr ** 2)

    if nodata_mask is not None:
        sigma0_linear[nodata_mask] = np.nan

    return sigma0_linear.astype(np.float32)


def interpolate_calibration_lut_grid(
    lines: Sequence[int],
    pixel_coords: Sequence[int],
    lut_values: np.ndarray,
    output_shape: Tuple[int, int],
) -> np.ndarray:
    """Interpolate sparse ESA calibration vector grid to full raster dimensions.

    Sentinel-1 calibration XML provides calibration vectors sampled at specific
    azimuth lines and range pixel coordinates. This function performs 2D bilinear
    interpolation over the (height, width) raster grid.

    Args:
        lines: 1D sequence of azimuth line indices (length N_lines).
        pixel_coords: 1D sequence of range pixel indices (length N_pixels).
        lut_values: 2D array of calibration factors of shape (N_lines, N_pixels).
        output_shape: Tuple (height, width) of the target raster.

    Returns:
        Interpolated 2D float32 array of shape (height, width).
    """
    height, width = output_shape
    lines_arr = np.asarray(lines, dtype=np.float64)
    pixels_arr = np.asarray(pixel_coords, dtype=np.float64)
    lut_arr = np.asarray(lut_values, dtype=np.float64)

    if lut_arr.shape != (len(lines_arr), len(pixels_arr)):
        raise ValueError(
            f"lut_values shape {lut_arr.shape} does not match (len(lines), len(pixels)) "
            f"= ({len(lines_arr)}, {len(pixels_arr)})."
        )

    target_y = np.arange(height, dtype=np.float64)
    target_x = np.arange(width, dtype=np.float64)

    # 1D interpolation along range (x) for each calibration vector line
    # shape: (N_lines, width)
    intermediate = np.zeros((len(lines_arr), width), dtype=np.float64)
    for i in range(len(lines_arr)):
        intermediate[i, :] = np.interp(target_x, pixels_arr, lut_arr[i, :])

    # 1D interpolation along azimuth (y) for each column
    # shape: (height, width)
    full_grid = np.zeros((height, width), dtype=np.float32)
    for j in range(width):
        full_grid[:, j] = np.interp(target_y, lines_arr, intermediate[:, j]).astype(np.float32)

    return full_grid


def linear_to_db(
    linear_intensity: np.ndarray,
    epsilon: float = DEFAULT_EPSILON,
    fill_invalid: float = np.nan,
) -> np.ndarray:
    """Convert linear backscatter intensity (sigma0) to decibels (dB).

    Formula:
        sigma0_dB = 10 * log10(max(linear_intensity, epsilon))

    Non-finite pixels (NaN, inf) and non-positive pixels (when epsilon <= 0)
    are mapped to fill_invalid.

    Args:
        linear_intensity: Array of linear sigma0 values, float32 or float64.
        epsilon: Lower clamp floor to prevent -inf. Defaults to 1e-7 (-70 dB).
        fill_invalid: Value to assign to invalid pixels (default: np.nan).

    Returns:
        Array of sigma0 in dB as float32.
    """
    arr = np.asarray(linear_intensity, dtype=np.float32)
    out = np.full_like(arr, fill_invalid, dtype=np.float32)

    # Valid mask: finite and strictly positive
    valid_mask = np.isfinite(arr) & (arr > 0)
    if not np.any(valid_mask):
        return out

    clamped = np.maximum(arr[valid_mask], epsilon)
    out[valid_mask] = (10.0 * np.log10(clamped)).astype(np.float32)

    return out


def stack_dual_pol_channels(
    vh_channel: np.ndarray,
    vv_channel: np.ndarray,
    order: Tuple[str, str] = OPERATIONAL_STACK_ORDER,
) -> np.ndarray:
    """Stack single-channel VH and VV rasters into 2-channel array for EXP-06.

    Enforces the EXP-06 Operational Contract:
        Ch0 = VH (Cross-Pol)
        Ch1 = VV (Co-Pol)

    Args:
        vh_channel: 2D array of VH data (float32, dB).
        vv_channel: 2D array of VV data (float32, dB).
        order: Tuple specifying channel order. Must be ('VH', 'VV').

    Returns:
        3D float32 array of shape (2, H, W).

    Raises:
        ValueError: If shapes mismatch, arrays are not 2D, or order is not ('VH', 'VV').
    """
    if order != ("VH", "VV"):
        raise ValueError(
            f"Invalid channel order {order}. EXP-06 operational contract strictly requires ('VH', 'VV')."
        )

    vh_arr = np.asarray(vh_channel, dtype=np.float32)
    vv_arr = np.asarray(vv_channel, dtype=np.float32)

    if vh_arr.ndim != 2 or vv_arr.ndim != 2:
        raise ValueError(
            f"Input channels must be 2D, got vh ndim={vh_arr.ndim}, vv ndim={vv_arr.ndim}."
        )

    if vh_arr.shape != vv_arr.shape:
        raise ValueError(
            f"Channel shape mismatch: VH shape {vh_arr.shape} != VV shape {vv_arr.shape}."
        )

    # Stack: axis 0 index 0 = VH, index 1 = VV
    stacked = np.stack([vh_arr, vv_arr], axis=0)
    return stacked.astype(np.float32)


def apply_nodata_datamask(
    raster: np.ndarray,
    data_mask: np.ndarray,
    nodata_value: float = np.nan,
) -> np.ndarray:
    """Apply dataMask to raster, setting invalid pixels to nodata_value.

    Sentinel Hub Process API dataMask convention:
        1 = valid ocean / observation pixel
        0 = invalid / no data / out-of-swath pixel

    Args:
        raster: 2D or 3D array of raster data.
        data_mask: 2D array matching the spatial dimensions of raster.
        nodata_value: Value to set for invalid pixels (default: np.nan).

    Returns:
        Raster with invalid pixels set to nodata_value.

    Raises:
        ValueError: If spatial dimensions do not match.
    """
    r_arr = np.asarray(raster).copy()
    m_arr = np.asarray(data_mask)

    spatial_shape = r_arr.shape[-2:]
    if m_arr.shape != spatial_shape:
        raise ValueError(
            f"dataMask shape {m_arr.shape} does not match raster spatial shape {spatial_shape}."
        )

    invalid_pixels = (m_arr == 0)

    if r_arr.ndim == 2:
        r_arr[invalid_pixels] = nodata_value
    elif r_arr.ndim == 3:
        for c in range(r_arr.shape[0]):
            r_arr[c, invalid_pixels] = nodata_value
    else:
        raise ValueError(f"Raster ndim must be 2 or 3, got {r_arr.ndim}.")

    return r_arr
