#!/usr/bin/env python
"""CLI for Ocean Sentinel Multi-Source Evidence Fusion V1.

Fuses multi-modal observations (SAR, temporal change, backward drift, AIS tracks,
and optical satellite observations) into an explainable Evidence Graph and
evidence-bounded candidate hypotheses.

Strict Scientific & Legal Boundary:
-----------------------------------
1. This tool assesses SPATIO-TEMPORAL EVIDENCE COMPATIBILITY only.
2. It does NOT perform legal attribution, declare responsible vessels, or claim culpability.
3. No single scalar "attribution probability" is generated.
4. Absence of AIS records does NOT prove vessel absence (negative-proof guard).
5. Multiple candidates may remain simultaneously plausible.
"""

from __future__ import annotations

import argparse
import json
import logging
from pathlib import Path
import sys
import time
from datetime import datetime, timedelta, timezone
from typing import Any, Dict, List, Optional

# Add src to sys.path
REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "src"))

from ocean_sentinel.drift import ProvenanceGateError
from ocean_sentinel.fusion import (
    CandidateHypothesis,
    CandidateVesselHypothesis,
    DerivationType,
    EvidenceFusionEngine,
    EvidenceItem,
    EvidenceType,
    FusionMode,
    ObservationStatus,
    ProvenanceClass,
    RelationshipType,
    SourceType,
    generate_deterministic_demo_fusion_fixture,
    load_evidence_from_detection_geojson,
    load_evidence_from_drift_geojson,
    load_evidence_from_temporal_geojson,
)

# Exit code contract
EXIT_SUCCESS = 0
EXIT_ERROR = 1
EXIT_PROVENANCE_REJECTION = 2
EXIT_INVALID_INPUT = 3

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(name)s: %(message)s")
logger = logging.getLogger("run_evidence_fusion")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Fuse multi-modal evidence (SAR, temporal, drift, AIS, optical) into an explainable Evidence Graph."
    )
    parser.add_argument(
        "--mode", "-m",
        type=str,
        choices=["demo", "physical"],
        default="demo",
        help="Operational mode: 'physical' (strictly requires verified operational feeds) or 'demo' (allows fixtures).",
    )
    parser.add_argument(
        "--detection-geojson",
        type=Path,
        default=None,
        help="Path to SAR detection GeoJSON artifact.",
    )
    parser.add_argument(
        "--temporal-geojson",
        type=Path,
        default=None,
        help="Path to temporal change GeoJSON artifact.",
    )
    parser.add_argument(
        "--drift-geojson", "-d",
        type=Path,
        default=None,
        help="Path to origin & drift GeoJSON artifact generated by run_origin_drift.py.",
    )
    parser.add_argument(
        "--ais-summary", "-a",
        type=Path,
        default=None,
        help="Path to AIS correlation summary JSON artifact generated by run_ais_correlation.py.",
    )
    parser.add_argument(
        "--optical-geojson",
        type=Path,
        default=None,
        help="Path to optical satellite observation GeoJSON artifact.",
    )
    parser.add_argument(
        "--output-dir", "-o",
        type=Path,
        default=REPO_ROOT / "outputs" / "evidence",
        help="Directory to export evidence graph, summary, and GeoJSON (default: outputs/evidence).",
    )
    parser.add_argument(
        "--output-prefix",
        type=str,
        default=None,
        help="Optional filename prefix for exported files.",
    )
    parser.add_argument(
        "--spatial-tolerance-m",
        type=float,
        default=5000.0,
        help="Spatial tolerance distance in meters for alignment evaluation (default: 5000.0).",
    )
    parser.add_argument(
        "--temporal-tolerance-hours",
        type=float,
        default=2.0,
        help="Temporal tolerance window in hours for alignment evaluation (default: 2.0).",
    )
    return parser


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()

    start_time = time.time()
    mode = FusionMode.PHYSICAL if args.mode == "physical" else FusionMode.DEMO

    print("=" * 80)
    print(f"OCEAN SENTINEL — MULTI-SOURCE EVIDENCE FUSION V1 [{mode.value} MODE]")
    print("=" * 80)

    # Initialize fusion engine
    engine = EvidenceFusionEngine(
        mode=mode,
        spatial_tolerance_m=args.spatial_tolerance_m,
        temporal_tolerance_seconds=args.temporal_tolerance_hours * 3600.0,
    )

    prefix = args.output_prefix or "demo_evidence_fusion"
    evidence_items: List[EvidenceItem] = []
    ais_summary: Optional[Dict[str, Any]] = None

    try:
        # Determine whether input files were supplied
        has_cli_inputs = any([
            args.detection_geojson,
            args.temporal_geojson,
            args.drift_geojson,
            args.ais_summary,
            args.optical_geojson,
        ])

        if not has_cli_inputs:
            if mode == FusionMode.PHYSICAL:
                print(
                    "\n[PROVENANCE GATE REJECTION] Physical mode requires verified operational inputs.\n"
                    "  No input files provided, and synthetic fixtures are forbidden in PHYSICAL mode.\n"
                    "  Status: BLOCKED — AWAITING_OPERATIONAL_SOURCE.",
                    file=sys.stderr,
                )
                return EXIT_PROVENANCE_REJECTION

            print("  No CLI input files provided. Ingesting deterministic multi-source DEMO fixture...")
            evidence_items, ais_summary = generate_deterministic_demo_fusion_fixture()
        else:
            print("  Ingesting provided input artifacts...")
            if args.detection_geojson:
                if not args.detection_geojson.is_file():
                    print(f"[ERROR] Detection file not found: {args.detection_geojson}", file=sys.stderr)
                    return EXIT_INVALID_INPUT
                items = load_evidence_from_detection_geojson(args.detection_geojson)
                evidence_items.extend(items)
                print(f"    Loaded {len(items)} SAR detection items from {args.detection_geojson.name}")

            if args.temporal_geojson:
                if not args.temporal_geojson.is_file():
                    print(f"[ERROR] Temporal file not found: {args.temporal_geojson}", file=sys.stderr)
                    return EXIT_INVALID_INPUT
                items = load_evidence_from_temporal_geojson(args.temporal_geojson)
                evidence_items.extend(items)
                print(f"    Loaded {len(items)} temporal change items from {args.temporal_geojson.name}")

            if args.drift_geojson:
                if not args.drift_geojson.is_file():
                    print(f"[ERROR] Drift file not found: {args.drift_geojson}", file=sys.stderr)
                    return EXIT_INVALID_INPUT
                items = load_evidence_from_drift_geojson(args.drift_geojson)
                evidence_items.extend(items)
                print(f"    Loaded {len(items)} drift trajectory/origin items from {args.drift_geojson.name}")

            if args.ais_summary:
                if not args.ais_summary.is_file():
                    print(f"[ERROR] AIS summary file not found: {args.ais_summary}", file=sys.stderr)
                    return EXIT_INVALID_INPUT
                with open(args.ais_summary, "r", encoding="utf-8") as f:
                    ais_summary = json.load(f)
                cand_count = len(ais_summary.get("candidate_vessels", []))
                print(f"    Loaded {cand_count} AIS candidate vessels from {args.ais_summary.name}")

        # Ingest evidence items into the engine
        for item in evidence_items:
            engine.ingest_evidence_item(item)

        print(f"\n  Total Evidence Items Ingested: {len(engine.evidence_store)}")

        # Synthesize candidate spill origin hypothesis
        # Look for drift origin hypothesis item in evidence store
        origin_item = None
        drift_traj_item = None
        for item in engine.evidence_store.values():
            if item.evidence_type == EvidenceType.DRIFT_ORIGIN_HYPOTHESIS.value:
                origin_item = item
            elif item.evidence_type == EvidenceType.DRIFT_TRAJECTORY.value:
                drift_traj_item = item

        origin_geom = origin_item.spatial_geometry if origin_item else None
        target_time = origin_item.observation_time if origin_item else None
        t_window = (target_time - timedelta(hours=args.temporal_tolerance_hours), target_time) if target_time else None

        origin_hyp = engine.synthesize_spill_origin_hypothesis(
            hypothesis_id="hypothesis_origin_cluster_01",
            subject_id=origin_item.source_id if origin_item else "candidate_spill_event",
            origin_geometry=origin_geom,
            temporal_window=t_window,
        )
        print(f"  Synthesized Spill Origin Hypothesis: {origin_hyp.hypothesis_id} -> {origin_hyp.overall_status}")

        # Synthesize candidate vessel hypotheses if AIS correlation available
        vessel_hyps: List[CandidateVesselHypothesis] = []
        if ais_summary:
            drift_hyp_id = origin_item.evidence_id if origin_item else "evidence_drift_origin"
            vessel_hyps = engine.synthesize_candidate_vessel_hypotheses(
                ais_correlation_summary=ais_summary,
                drift_hypothesis_id=drift_hyp_id,
            )
            print(f"  Synthesized {len(vessel_hyps)} Candidate Vessel Hypotheses.")

    except ProvenanceGateError as pge:
        print(f"\n[PROVENANCE GATE REJECTION] Execution blocked by scientific gate:\n  {pge}", file=sys.stderr)
        print("  Rationale: PHYSICAL mode forbids synthetic fixtures or unverified external data.", file=sys.stderr)
        print("  Workaround: Use --mode demo for synthetic verification.", file=sys.stderr)
        return EXIT_PROVENANCE_REJECTION
    except Exception as e:
        print(f"\n[ERROR] Multi-Source Evidence Fusion failed: {e}", file=sys.stderr)
        logger.exception("Fusion pipeline failure")
        return EXIT_ERROR

    elapsed = time.time() - start_time

    # Export artifacts
    args.output_dir.mkdir(parents=True, exist_ok=True)
    graph_path = args.output_dir / f"{prefix}_evidence_graph.json"
    summary_path = args.output_dir / f"{prefix}_evidence_summary.json"
    geojson_path = args.output_dir / f"{prefix}_evidence.geojson"

    graph_dict = engine.graph.to_dict()
    summary_dict = engine.export_summary()
    geojson_dict = engine.export_geojson()

    with open(graph_path, "w", encoding="utf-8") as f:
        json.dump(graph_dict, f, indent=2)
    with open(summary_path, "w", encoding="utf-8") as f:
        json.dump(summary_dict, f, indent=2)
    with open(geojson_path, "w", encoding="utf-8") as f:
        json.dump(geojson_dict, f, indent=2)

    # Display results summary
    print("\n" + "=" * 80)
    print("EVIDENCE FUSION — CANDIDATE VESSEL HYPOTHESES")
    print("=" * 80)
    print(f"{'MMSI':<12} {'Vessel Name':<20} {'Status':<32} {'Score':<8} {'Indep Clusters'}")
    print("-" * 80)
    for vh in vessel_hyps:
        name = vh.vessel_name or "UNKNOWN"
        print(
            f"{vh.mmsi:<12} {name:<20} {vh.overall_status:<32} "
            f"{vh.evidence_compatibility_score:<8.4f} {vh.independent_support_cluster_count}"
        )

    print("-" * 80)
    print(f"MULTIPLE PLAUSIBLE CANDIDATES: {summary_dict['multiple_plausible_candidates']} "
          f"({summary_dict['plausible_candidate_count']} plausible vessels)")
    print(f"DEPENDENCY CYCLES DETECTED:    {graph_dict['metadata']['has_dependency_cycles']}")
    print("-" * 80)
    print("OUTPUT ARTIFACTS:")
    print(f"  Evidence Graph JSON:    {graph_path}")
    print(f"  Evidence Summary JSON:  {summary_path}")
    print(f"  Spatial GeoJSON:        {geojson_path}")
    print("-" * 80)
    print("SCIENTIFIC & LEGAL BOUNDARIES:")
    for b in summary_dict["scientific_boundaries"]:
        print(f"  * {b}")
    print(f"  Elapsed Time:           {elapsed:.4f} s")
    print("=" * 80)

    return EXIT_SUCCESS


if __name__ == "__main__":
    sys.exit(main())
