#!/usr/bin/env python
"""CLI for Ocean Sentinel AIS Spatio-Temporal Correlation V1.

Correlates time-indexed candidate drift trajectories and origin regions with vessel AIS tracks.
Produces RFC 7946 GeoJSON and machine-readable JSON candidate vessel summaries.

Strict Scientific & Legal Boundary:
-----------------------------------
This tool assesses SPATIO-TEMPORAL EVIDENCE COMPATIBILITY only.
It does NOT perform legal attribution or claim vessel responsibility.
"""

from __future__ import annotations

import argparse
import json
import logging
import sys
import time
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple, Union

# Add src to sys.path
REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "src"))

from shapely.geometry import shape

from ocean_sentinel.ais import (
    AISCorrelationMode,
    AISProvenance,
    AISRecord,
    CandidateHypothesisPoint,
    correlate_vessel_tracks,
    filter_and_assemble_vessel_tracks,
    generate_deterministic_demo_ais_fixture,
    serialize_ais_correlation_to_geojson,
    serialize_ais_correlation_summary,
)
from ocean_sentinel.drift import ProvenanceGateError

# Exit code contract
EXIT_SUCCESS = 0
EXIT_ERROR = 1
EXIT_PROVENANCE_REJECTION = 2
EXIT_INVALID_INPUT = 3

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(name)s: %(message)s")
logger = logging.getLogger("run_ais_correlation")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Correlate time-indexed candidate drift trajectories and origin hypotheses with AIS tracks."
    )
    parser.add_argument(
        "--drift-geojson", "-d",
        type=Path,
        required=True,
        help="Path to drift trajectory GeoJSON artifact generated by run_origin_drift.py.",
    )
    parser.add_argument(
        "--drift-summary", "-s",
        type=Path,
        default=None,
        help="Optional path to drift summary JSON artifact.",
    )
    parser.add_argument(
        "--ais-feed", "-a",
        type=Path,
        default=None,
        help="Path to raw AIS JSON/GeoJSON feed (if omitted, uses deterministic DEMO fixture).",
    )
    parser.add_argument(
        "--mode", "-m",
        type=str,
        choices=["demo", "physical"],
        default="demo",
        help="Execution mode: 'physical' (strictly requires verified AIS feed) or 'demo' (allows fixtures).",
    )
    parser.add_argument(
        "--max-interpolation-gap-hours",
        type=float,
        default=2.0,
        help="Maximum gap duration in hours across which vessel trajectory is interpolated (default: 2.0).",
    )
    parser.add_argument(
        "--max-plausible-speed-knots",
        type=float,
        default=60.0,
        help="Maximum plausible vessel speed in knots (operational filtering heuristic, default: 60.0).",
    )
    parser.add_argument(
        "--output-dir", "-o",
        type=Path,
        default=REPO_ROOT / "outputs" / "ais",
        help="Directory to export correlation GeoJSON and summary JSON (default: outputs/ais).",
    )
    parser.add_argument(
        "--output-prefix",
        type=str,
        default=None,
        help="Optional filename prefix for exported files.",
    )
    return parser


def load_drift_artifacts(
    drift_geojson_path: Path,
    drift_summary_path: Optional[Path] = None,
) -> Tuple[List[CandidateHypothesisPoint], Any, Any, str, datetime, float]:
    """Parse candidate origin hypotheses and boundary polygons from drift GeoJSON."""
    with open(drift_geojson_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    if data.get("type") != "FeatureCollection":
        raise ValueError(f"Expected GeoJSON FeatureCollection in {drift_geojson_path.name}")

    features = data.get("features", [])
    meta = data.get("metadata", {})
    event_id = meta.get("event_id", "drift_event")
    obs_t_str = meta.get("observation_time", "2024-05-13T00:00:00+00:00")
    obs_dt = datetime.fromisoformat(obs_t_str.replace("Z", "+00:00"))

    # Attempt to load duration and timestep from summary
    duration_hours = 24.0
    timestep_seconds = 1800.0
    direction = meta.get("direction", "BACKWARD")

    summary_file = drift_summary_path
    if not summary_file:
        cand_p = drift_geojson_path.parent / f"{drift_geojson_path.stem}_summary.json"
        if cand_p.is_file():
            summary_file = cand_p

    if summary_file and summary_file.is_file():
        try:
            with open(summary_file, "r", encoding="utf-8") as sf:
                sdata = json.load(sf)
            params = sdata.get("model_parameters", {})
            duration_hours = params.get("duration_hours", 24.0)
            timestep_seconds = params.get("timestep_seconds", 1800.0)
            direction = sdata.get("direction", direction)
        except Exception:
            pass

    sign = -1.0 if direction == "BACKWARD" else 1.0
    total_seconds = duration_hours * 3600.0

    hypotheses: List[CandidateHypothesisPoint] = []
    origin_polygon = None
    envelope_polygon = None

    for feat in features:
        props = feat.get("properties", {})
        ftype = props.get("feature_type")

        if ftype == "candidate_origin_region":
            origin_polygon = shape(feat["geometry"])
        elif ftype == "trajectory_envelope":
            envelope_polygon = shape(feat["geometry"])
        elif ftype == "trajectory_line":
            part_id = props.get("particle_id", "part")
            w_factor = props.get("windage_factor", 0.02)
            coords = feat.get("geometry", {}).get("coordinates", [])
            n_pts = len(coords)
            if n_pts > 0:
                dt_step = total_seconds / max(1, n_pts - 1)
                for step_idx, c in enumerate(coords):
                    t_step = obs_dt + timedelta(seconds=sign * step_idx * dt_step)
                    is_term = (step_idx == n_pts - 1)
                    hypotheses.append(
                        CandidateHypothesisPoint(
                            longitude=c[0],
                            latitude=c[1],
                            timestamp=t_step,
                            particle_id=part_id,
                            windage_factor=w_factor,
                            trajectory_step=step_idx,
                            is_origin_endpoint=is_term,
                        )
                    )

    t_terminal = obs_dt + timedelta(seconds=sign * total_seconds)
    return hypotheses, origin_polygon, envelope_polygon, event_id, t_terminal, duration_hours


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()

    start_time = time.time()
    mode = AISCorrelationMode.PHYSICAL if args.mode.lower() == "physical" else AISCorrelationMode.DEMO

    print("=" * 80)
    print("OCEAN SENTINEL — AIS SPATIO-TEMPORAL CORRELATION V1")
    print("=" * 80)
    print(f"  Drift GeoJSON File:     {args.drift_geojson}")
    print(f"  Execution Mode:         {mode.value}")
    print(f"  AIS Data Feed:          {args.ais_feed or 'Deterministic DEMO Fixture'}")
    print(f"  Max Interpolation Gap:  {args.max_interpolation_gap_hours:.1f} hours")
    print(f"  Output Directory:       {args.output_dir}")
    print("-" * 80)

    # 1. Load drift hypotheses
    try:
        hypotheses, origin_poly, env_poly, event_id, t_terminal, duration_hours = load_drift_artifacts(
            args.drift_geojson, args.drift_summary
        )
    except (FileNotFoundError, json.JSONDecodeError, ValueError) as ve:
        print(f"\n[INVALID INPUT] Failed to load drift artifacts: {ve}", file=sys.stderr)
        return EXIT_INVALID_INPUT
    except Exception as e:
        print(f"\n[ERROR] Failed to load drift artifacts: {e}", file=sys.stderr)
        return EXIT_ERROR

    print(f"  Event ID:               {event_id}")
    print(f"  Candidate Hypotheses:   {len(hypotheses)}")
    print(f"  Origin Region Polygon:  {'Present' if origin_poly else 'None'}")
    print(f"  Trajectory Envelope:    {'Present' if env_poly else 'None'}")
    print(f"  Target Origin Time:     {t_terminal.isoformat()}")
    print("-" * 80)

    # 2. Ingest AIS records
    raw_records: List[AISRecord] = []
    if args.ais_feed is not None:
        try:
            with open(args.ais_feed, "r", encoding="utf-8") as f:
                raw_json = json.load(f)
            # Parse records
            items = raw_json.get("records", raw_json if isinstance(raw_json, list) else [])
            for item in items:
                prov_val = item.get("provenance")
                if prov_val is None:
                    prov_val = (
                        AISProvenance.VERIFIED_OPERATIONAL_FEED.value
                        if item.get("is_authoritative")
                        else AISProvenance.SYNTHETIC_DEMO_FEED.value
                    )
                raw_records.append(
                    AISRecord(
                        mmsi=item["mmsi"],
                        timestamp=datetime.fromisoformat(item["timestamp"].replace("Z", "+00:00")),
                        longitude=item["longitude"],
                        latitude=item["latitude"],
                        sog_knots=item.get("sog_knots"),
                        cog_degrees=item.get("cog_degrees"),
                        imo=item.get("imo"),
                        vessel_name=item.get("vessel_name"),
                        vessel_type=item.get("vessel_type"),
                        navigation_status=item.get("navigation_status"),
                        source_identifier=item.get("source_identifier", "external_feed"),
                        provenance=prov_val,
                        adapter_id=item.get("adapter_id"),
                        verification_token=item.get("verification_token"),
                    )
                )
        except (FileNotFoundError, json.JSONDecodeError, KeyError, ValueError) as e:
            print(f"\n[INVALID INPUT] Failed to read AIS feed: {e}", file=sys.stderr)
            return EXIT_INVALID_INPUT
        except Exception as e:
            print(f"\n[ERROR] Failed to read AIS feed: {e}", file=sys.stderr)
            return EXIT_ERROR
    else:
        # Default deterministic demo fixture anchored to candidate origin
        orig_lon = float(origin_poly.centroid.x) if origin_poly else -90.438
        orig_lat = float(origin_poly.centroid.y) if origin_poly else 26.927
        raw_records = generate_deterministic_demo_ais_fixture(
            origin_lon=orig_lon,
            origin_lat=orig_lat,
            origin_time=t_terminal,
        )

    # 3. Assemble and filter tracks
    tracks = filter_and_assemble_vessel_tracks(
        raw_records,
        max_plausible_speed_knots=args.max_plausible_speed_knots,
        max_interpolation_gap_seconds=args.max_interpolation_gap_hours * 3600.0,
    )
    print(f"  Total Vessels Ingested: {len(tracks)}")

    # 4. Spatio-temporal correlation
    try:
        candidates = correlate_vessel_tracks(
            tracks=tracks,
            hypotheses=hypotheses,
            candidate_origin_polygon=origin_poly,
            trajectory_envelope_polygon=env_poly,
            max_interpolation_gap_seconds=args.max_interpolation_gap_hours * 3600.0,
            mode=mode,
        )
    except ProvenanceGateError as pge:
        print(f"\n[PROVENANCE GATE REJECTION] Execution blocked by scientific gate: {pge}", file=sys.stderr)
        print("  Rationale: PHYSICAL mode forbids synthetic AIS feeds or unverified data.", file=sys.stderr)
        print("  Workaround: Use --mode demo for non-physical pipeline verification.", file=sys.stderr)
        return EXIT_PROVENANCE_REJECTION
    except Exception as e:
        print(f"\n[ERROR] AIS correlation failed: {e}", file=sys.stderr)
        logger.exception("Correlation failure")
        return EXIT_ERROR

    elapsed = time.time() - start_time

    # 5. Export artifacts
    args.output_dir.mkdir(parents=True, exist_ok=True)
    prefix = args.output_prefix or f"{event_id}_ais_correlation"
    geojson_path = args.output_dir / f"{prefix}.geojson"
    json_path = args.output_dir / f"{prefix}_summary.json"

    geojson_dict = serialize_ais_correlation_to_geojson(
        candidates=candidates,
        tracks=tracks,
        candidate_origin_polygon=origin_poly,
        trajectory_envelope_polygon=env_poly,
        mode=mode,
        event_id=event_id,
    )
    summary_dict = serialize_ais_correlation_summary(
        candidates=candidates,
        tracks=tracks,
        mode=mode,
        event_id=event_id,
    )

    with open(geojson_path, "w", encoding="utf-8") as f:
        json.dump(geojson_dict, f, indent=2)
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(summary_dict, f, indent=2)

    # 6. Display Summary Table
    print("\n" + "=" * 80)
    print("CANDIDATE VESSEL SPATIO-TEMPORAL COMPATIBILITY RANKING")
    print("=" * 80)
    print(f"{'MMSI':<12} {'Vessel Name':<20} {'Type':<18} {'Score':<8} {'Min Dist':<12} {'Time Offset':<12} {'Inside Origin'}")
    print("-" * 80)
    for c in candidates:
        name = c.vessel_name or "UNKNOWN"
        vtype = c.vessel_type or "UNKNOWN"
        dist_str = f"{c.min_distance_to_origin_m:,.0f} m"
        offset_str = f"{c.temporal_offset_seconds / 3600.0:+.1f} h"
        inside_str = "YES" if c.inside_candidate_origin_region else "NO"
        print(f"{c.mmsi:<12} {name:<20} {vtype:<18} {c.evidence_compatibility_score:<8.4f} {dist_str:<12} {offset_str:<12} {inside_str}")

    print("-" * 80)
    print("OUTPUT ARTIFACTS:")
    print(f"  GeoJSON Correlation:    {geojson_path}")
    print(f"  Summary JSON:           {json_path}")
    print("-" * 80)
    print("SCIENTIFIC & LEGAL NOTICE:")
    for lim in summary_dict["scientific_limitations"]:
        print(f"  * {lim}")
    print(f"  Elapsed Time:           {elapsed:.4f} s")
    print("=" * 80)
    return EXIT_SUCCESS


if __name__ == "__main__":
    sys.exit(main())
